### ISSUE TITLE
Initial Commit

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/jekyll-velox#1]
> As a developer I must have some kind of starting point, in order to get ready for development.

## Tasks

- [x] Add common project files, e.g. `readme.md`, `license.md` ...
- [x] Setup an advanced asset management using Gulp and Laravel Elixir.
- [x] Add default dependencies used for project.
- [x] Setup default Jekyll project to run on continous integration runnes such as GitHub-Pages.
- [x] Add common pages, e.g. the homepage or the page not found (404) error page.
