### ISSUE TITLE
Initial Commit

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/jekyll-velox#1]
> As a file based CMS, I must provide some point in order to start for development.

## Tasks

- [x] Add common project files e.g. `readme.md`, `license.md` ...
- [x] Add advanced asset management using Gulp and Laravel Elixir.
- [x] Add the default dependencies and assets used for the project.
- [x] Scaffold a dead simple Jekyll project, ready to use on GitHub.
- [x] Add some default data and includes, in order to speed up development.
- [x] Add the default layouts and pages, e.g. the homepage and the page not found (404).

**Comment by sirthxalot** [comment]
![image](https://cloud.githubusercontent.com/assets/6856248/21755945/ed659318-d61a-11e6-93ad-edf96b66f121.png)

**Comment by sirthxalot** [comment]
## Image

![image](https://cloud.githubusercontent.com/assets/6856248/21755945/ed659318-d61a-11e6-93ad-edf96b66f121.png)
