### ISSUE TITLE
Header Segment

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/jekyll-velox#2]
Okay lets begin to scaffold the header (navbar top) segment.

## TASKS

- [x] Add the page layout.
- [x] Scaffold the header segment.
- [x] Add the header brand.
- [x] Add the header menu.

**Comment by sirthxalot** [comment]
![image](https://cloud.githubusercontent.com/assets/6856248/21966537/75c149fa-db75-11e6-892e-65531a43a102.png)
